name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Build Godot
      uses: josephbmanley/build-godot-action@v1.3.1
      with:
        # Name of the exported binary
        name: Color Bluff
        # Name of the preset in `export_presets.cfg` to use
        preset: HTML5
        # Optional name of the subdirectory to put exported project in
        subdirectory: export
        # Set true to output an artifact zip file
        # package: # optional
